name: "Release"
on:
  push:
    tags:
      - 'v*'

env:
  GAME_SUBDIRECTORY: "godot-manager"
  GODOT_VERSION: "3.4.3"
  GODOT_VERSION_MODIFIER: "stable.mono"
  EXPORT_NAME: "GodotManager"
  CUSTOM_ICON: "true"
  ITCHIO_USERNAME: "eumario"
  ITCHIO_GAME: "godot-manager"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      release_upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version-without-v }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Get version name
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version-without-v }}
          body: ""
          draft: false
          prerelease: false
  
  export:
    name: Export
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        include:
          - platform: windows
            extension: .exe
            type: executable
          - platform: mac
            extension: .zip
            type: archive
          - platform: linux
            extension: .x86_64
            type: executable
    container:
      image: eumario/github-actions-ci:0.1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.${GODOT_VERSION_MODIFIER} ~/.local/share/godot/templates/${GODOT_VERSION}.${GODOT_VERSION_MODIFIER}
      - name: File information setup
        id: file-information
        env:
          EXPORT_PLATFORM: ${{ matrix.platform }}
          FILE_EXTENSION: ${{ matrix.extension }}
        run: |
          if [ "${EXPORT_PLATFORM}" = "html" ]
          then
            echo "::set-output name=name::index${FILE_EXTENSION}"
          else
            echo "::set-output name=name::${EXPORT_NAME}${FILE_EXTENSION}"
          fi
      - name: Build
        id: build
        env:
          EXPORT_PLATFORM: ${{ matrix.platform }}
          EXPORT_FILENAME: ${{ steps.file-information.outputs.name }}
        run: |
          buildPath="${GITHUB_WORKSPACE}/build/${EXPORT_PLATFORM}"
          filePath="${buildPath}/${EXPORT_FILENAME}"
          mkdir -v -p "${buildPath}"
          dotnet restore
          godot -v --path "./$GAME_SUBDIRECTORY" --export-debug "${EXPORT_PLATFORM}" "${filePath}"
          echo "::set-output name=build_directory::${buildPath}"
          echo "::set-output name=build_file::${filePath}"
      - name: Archive
        id: archive
        env:
          EXPORT_PLATFORM: ${{ matrix.platform }}
          BUILD_DIRECTORY: ${{ steps.build.outputs.build_directory }}
          BUILD_FILE: ${{ steps.build.outputs.build_file }}
          FILE_TYPE: ${{ matrix.type }}
          VERSION: ${{ needs.release.outputs.version }}
        run: |
          rootBuildPath="${GITHUB_WORKSPACE}/build"
          formattedExportName="$( echo ${EXPORT_NAME} | sed 's/./\L&/g' | sed 's/ /-/g' )"
          filename="${formattedExportName}-${EXPORT_PLATFORM}-v${VERSION}.zip"
          filePath="${rootBuildPath}/${filename}"
          if [ "${FILE_TYPE}" = "executable" ]
          then
            cd "${BUILD_DIRECTORY}" && zip -r "${filePath}" *
          else
            mv "${BUILD_FILE}" "${filePath}"
          fi
          echo "::set-output name=path::${filePath}"
          echo "::set-output name=filename::${filename}"
      - name: Upload Release Asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.archive.outputs.path }}
      - name: Upload on itch
        env:
          CHANNEL: ${{ matrix.platform }}
          PACKAGE: ${{ steps.archive.outputs.path }}
          VERSION: ${{ needs.release.outputs.version }}
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        if: ${{ env.BUTLER_API_KEY != '' && env.ITCHIO_USERNAME != '' && env.ITCHIO_GAME != '' }}
        run: butler push --userversion=${VERSION} "${PACKAGE}" ${ITCHIO_USERNAME}/${ITCHIO_GAME}:${CHANNEL}